version: "3.5"

services:
  api01: &api
    image: spring-exemplo
    hostname: api01
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=123
      - PORT=8081
    ports:
      - "3001:8081"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=123
      - PORT=8082
    ports:
      - "3002:8082"

  nginx:
    image: nginx:latest
    volumes:
      - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
