server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
  jmx:
    enabled: false
  aop:
    auto: false
    proxy-target-class: false
  application:
    admin:
       enabled: false
